  library(MetricGraph)
  library(rSPDE)

    library(sp)
  line1 <- Line(rbind(c(0,0),c(1,0)))
  line2 <- Line(rbind(c(0,0),c(0,1)))
  line3 <- Line(rbind(c(0,1),c(-1,1)))
  theta <- seq(from=pi,to=3*pi/2,length.out = 20)
  line4 <- Line(cbind(sin(theta),1+ cos(theta)))
  Lines = SpatialLines(list(Lines(list(line1),ID="1"),
                                Lines(list(line2),ID="2"),
                                Lines(list(line3),ID="3"),
                                Lines(list(line4),ID="4")))
  graph <- metric_graph$new(lines = Lines)
  graph$plot()

  graph$build_mesh(h = 0.01)

  graph$compute_fem()

  sigma <- 1.3
  r <- 0.2 # range
  nu <- 0.9
  rspde.order <- 2

  op <- matern.operators(nu = nu, range = r, sigma = sigma, 
                         m = rspde.order, graph = graph)

  op <- matern.operators(nu = nu, kappa = op$kappa, sigma = 1/op$tau, 
                         m = rspde.order, graph = graph, parameterization = "graph")                         

  u <- simulate(op)
graph$plot_function(u, plotly = TRUE)

obs.per.edge <- 200
obs.loc <- NULL
for(i in 1:graph$nE) {
  obs.loc <- rbind(obs.loc,
                   cbind(rep(i,obs.per.edge), runif(obs.per.edge)))
}
n.obs <- obs.per.edge*graph$nE
A <- graph$mesh_A(obs.loc)

sigma.e <- 0.1

x1 <- runif(nrow(obs.loc))
x2 <- rexp(nrow(obs.loc))

Y <- 1 + 2*x1 - 3*x2 + as.vector(A %*% u + sigma.e * rnorm(n.obs))


df_data <- data.frame(y = Y, edge_number = obs.loc[,1],
                         distance_on_edge = obs.loc[,2],
                        x1 = x1, x2 = x2)

graph$add_observations(data = df_data, normalized = TRUE)

op_est <- matern.operators(m = rspde.order, graph = graph, parameterization = "matern")



fit <- rspde_lme(y ~ x1 + x2, model = op_est)

summary(fit)

fit <- graph_lme(y ~ x1 + x2, graph = graph, model = "wm")

summary(fit)



  library(sp)
  line1 <- Line(rbind(c(0,0),c(1,0)))
  line2 <- Line(rbind(c(0,0),c(0,1)))
  line3 <- Line(rbind(c(0,1),c(-1,1)))
  theta <- seq(from=pi,to=3*pi/2,length.out = 20)
  line4 <- Line(cbind(sin(theta),1+ cos(theta)))
  Lines = SpatialLines(list(Lines(list(line1),ID="1"),
                                Lines(list(line2),ID="2"),
                                Lines(list(line3),ID="3"),
                                Lines(list(line4),ID="4")))
  graph <- metric_graph$new(lines = Lines)
  graph$plot()



graph$build_mesh(h = 0.01)
  sigma <- 23
  kappa <- 15
  nu <- 0.8
  rspde.order <- 2
  op <- matern.operators(nu = nu, kappa = kappa, sigma = sigma, 
                         parameterization = "graph",
                         m = rspde.order, graph = graph)                     

u <- simulate(op)
# graph$plot_function(u, plotly = TRUE)

obs.per.edge <- 50
obs.loc <- NULL
for(i in 1:graph$nE) {
  obs.loc <- rbind(obs.loc,
                   cbind(rep(i,obs.per.edge), runif(obs.per.edge)))
}
n.obs <- obs.per.edge*graph$nE
A <- graph$mesh_A(obs.loc)


    sigma.e <- 0.1

    x1 <- obs.loc[,1]
    x2 <- obs.loc[,2]

    Y <- 2 + 2*x1 - 3*x2 + as.vector(A %*% u + sigma.e * rnorm(n.obs))

df_data <- data.frame(y = Y, edge_number = obs.loc[,1],
                        distance_on_edge = obs.loc[,2],
                        x1 = x1, x2 = x2)

graph$clear_observations()
graph$add_observations(data = df_data, normalized = TRUE)

fit <- graph_lme(y ~ x1 + x2, graph = graph, model = "WM", parallel=TRUE)

summary(fit)
