on:
  push:
    branches:
      - devel
      
name: devel_setup

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2 
      - run:  |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          sed -i .bak '/vignettes/d' .Rbuildignore
          sed -i .bak '/#'\'' tryCatch({/d' R/inla_rspde.R
          sed -i .bak '/Could not run the example/d' R/inla_rspde.R
          sed -i .bak 's/donttest{ #tryCatch version/donttest{ #devel version/' R/inla_rspde.R
          sed -i .bak 's/#stable\.tag/#devel\.tag/' R/inla_rspde.R
          sed -i .bak 's/#stable\.tryCatch/#devel\.tag/' R/inla_rspde.R
          sed -i .bak 's/R.rsp/knitr/' DESCRIPTION
          html_files=$(shopt -s nullglob dotglob; echo vignettes/*.html)
          asis_files=$(shopt -s nullglob dotglob; echo vignettes/*.asis)
          if (( ${#html_files} ))
          then
            git rm vignettes/*.html
          fi
          if (( ${#asis_files} ))
          then
            git rm vignettes/*.asis
          fi
          git add R/inla_rspde.R
          git add .Rbuildignore
          git add DESCRIPTION
          git commit -m "Doing the setup"
          git push
