on:
  push:
    branches:
      - devel-src

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          extra-repositories: "https://inla.r-inla-download.org/R/testing https://mugglejinx.github.io/drat/"

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies on Linux (GL)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libglu1-mesa-dev libeigen3-dev
          sudo ln -s /usr/bin/gcc /usr/local/bin/gcc
          sudo ln -s /usr/bin/g++ /usr/local/bin/g++          

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             pkgdown
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'library(rmarkdown); rmarkdown::render("index.Rmd", "md_document")'     
          cp index_files/figure-markdown_strict/* man/figures/
          sed -i 's/index_files/man/' index.md
          sed -i 's/figure-markdown_strict/figures/' index.md
          git add *
          git commit -m "adding index.md and figures"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
