on:
  push:
    branches:
      - devel-src
  pull_request:
    branches:
      - devel
      - devel-src

name: R-CMD-check-mac

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://inla.r-inla-download.org/R/testing https://inlabru-org.r-universe.dev'

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          arch -arm64 brew install mimalloc
          brew install --cask xquartz
          brew install pkg-config proj@9 gdal gcc eigen gcc@14
          sudo mkdir -p /usr/local/include
          sudo mkdir -p /usr/local/bin
          sudo ln -s $(brew --prefix gcc@14)/bin/gcc-14 /usr/local/bin/gcc
          sudo ln -s $(brew --prefix gcc@14)/bin/g++-14 /usr/local/bin/g++
          sudo ln -s $(brew --prefix eigen)/include/eigen3 /usr/local/include/eigen3
          echo "export DYLD_LIBRARY_PATH=$(brew --prefix mimalloc)/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Link mimalloc for INLA
        if: runner.os == 'macOS'
        run: |
          mkdir -p /Users/runner/work/_temp/Library/INLA/bin/mac.arm64/malloc/
          ln -s $(brew --prefix mimalloc)/lib/libmimalloc.2.1.dylib /Users/runner/work/_temp/Library/INLA/bin/mac.arm64/malloc/libmimalloc.2.1.dylib

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             rcmdcheck
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'

  retry-on-failure:
    needs: R-CMD-check
    if: ${{ failure() && github.run_attempt < 3 }}
    runs-on: ${{ matrix.config.os }}
    name: Retry R-CMD-check (${{ matrix.config.os }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://inla.r-inla-download.org/R/testing https://inlabru-org.r-universe.dev'

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          arch -arm64 brew install mimalloc
          brew install --cask xquartz
          brew install pkg-config proj@9 gdal gcc eigen gcc@14
          sudo mkdir -p /usr/local/include
          sudo mkdir -p /usr/local/bin
          sudo ln -s $(brew --prefix gcc@14)/bin/gcc-14 /usr/local/bin/gcc
          sudo ln -s $(brew --prefix gcc@14)/bin/g++-14 /usr/local/bin/g++
          sudo ln -s $(brew --prefix eigen)/include/eigen3 /usr/local/include/eigen3
          echo "export DYLD_LIBRARY_PATH=$(brew --prefix mimalloc)/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Link mimalloc for INLA
        if: runner.os == 'macOS'
        run: |
          mkdir -p /Users/runner/work/_temp/Library/INLA/bin/mac.arm64/malloc/
          ln -s $(brew --prefix mimalloc)/lib/libmimalloc.2.1.dylib /Users/runner/work/_temp/Library/INLA/bin/mac.arm64/malloc/libmimalloc.2.1.dylib

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             rcmdcheck
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'