on:
  push:
    branches:
      - stable

name: stable_setup
  
jobs:
    stable_setup:
      runs-on: ubuntu-20.04
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v2      
        
        - name: Merge with stable-src and accept all incoming changes
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"              
            git config pull.rebase true
            git fetch origin
            git checkout stable-src
            git merge -X theirs stable --no-edit --no-commit --no-ff     
            git checkout --theirs .
            git add . 
            git reset -- src/
            sed -i 's/NeedsCompilation: no/NeedsCompilation: yes/' DESCRIPTION
            git add DESCRIPTION
            git commit -m "Doing the setup"
            git push origin stable-src --force
          shell: bash
